# pandas-challenge

Please take into account this code was run with the kernel: Anaconda 3 (Python3.9.13)
